config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books do
    member do
      get 'loan'
      get 'return'
    end
  end

  resources :rentals, only: :index

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :rentals, dependent: :destroy

  validates :title, presence: true

  enum status: { available: 0, loaned: 1 }
end

app/models/rental.rb
# frozen_string_literal: true

class Rental < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :status, presence: true

  enum status: { loaned: 0, returned: 1 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :rentals

  validates :first_name, :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(
      first_name: data['first_name'],
      last_name: data['last_name'],
      email: data['email'],
      password: Devise.friendly_token[0, 20]
    )
    user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :find_book, only: %i[edit show update destroy loan return]

  def index
    @books = Book.order(title: :asc).decorate
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params_book)

    if @book.save
      redirect_to books_path, notice: I18n.t('message_of_addition')
    else
      render :new
    end
  end

  def update
    if @book.update(params_book)
      redirect_to books_path, notice: I18n.t('message_of_modification')
    else
      render :edit
    end
  end

  def destroy
    message = @book.destroy ? 'message_of_deletion' : 'message_of_deletion_fail'
    redirect_to books_path, notice: I18n.t(message)
  end

  def loan
    change_status(:loan, I18n.t('message_of_loaning'))
  end

  def return
    change_status(:return, I18n.t('message_of_returning'))
  end

  private

  def params_book
    params.require(:book).permit(:title, :description)
  end

  def find_book
    @book = Book.find(params[:id]).decorate
  end

  def change_status(current_status, notice)
    message = BookService.call(current_status, @book, current_user)

    if message.nil?
      redirect_to books_path, notice: notice
    else
      redirect_to books_path, error: message
    end
  end
end

app/controllers/rentals_controller.rb
# frozen_string_literal: true

class RentalsController < ApplicationController
  def index
    @rentals = Rental.includes(:book, :user).order(created_at: :desc)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    before_action :set_user, only: :google_oauth2

    def google_oauth2
      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
        # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
    end

    private

    def set_user
      @user = User.from_omniauth(request.env['omniauth.auth'])
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success' then 'alert-success'
    when 'error' then 'alert-danger'
    when 'alert' then 'alert-warning'
    when 'notice' then 'alert-info'
    else
      'alert-info'
    end
  end
end

app/views/books/_book.html.haml
%tr
  %td= link_to book.title, book_path(book)
  %td= book.description
  %td{align: 'center'}= book.status
  %td= link_to t('edit'), edit_book_path(book), class: 'btn btn-sm btn-secondary'
  %td= link_to t('destroy'), book, method: :delete, data: { confirm: t('are_you_sure') }, class: 'btn btn-sm btn-danger'
  %td{align: 'center'}= book.loan_return_url(current_user)

app/views/books/_form.html.haml
= simple_form_for @book do |f|
  = f.input :title
  = f.input :description, as: :text
  = f.button :submit

app/views/books/edit.html.haml
= render 'form'

app/views/books/index.html.haml
%h1
  = Book.model_name.plural.humanize
  = link_to t('add'), new_book_path, class: 'btn btn-sm btn-success'

%table.table.table-striped
  %thead
    %tr
      %th{scope: 'col'}= Book.human_attribute_name(:title)
      %th{scope: 'col'}= Book.human_attribute_name(:description)
      %th{scope: 'col'}= Book.human_attribute_name(:status)
      %th{scope: 'col'}
      %th{scope: 'col'}
      %th{scope: 'col'}
  #tbody
  = render @books

app/views/books/new.html.haml
= render 'form'

app/views/books/show.html.haml
%h1= @book.title
%p= @book.description
%p
  = @book.status
  = @book.loan_return_url(current_user)

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
  %div{ class: "alert #{bootstrap_class_for(type)} alert-dismissible fade show", role: 'alert' }
    %button.close{ 'data-dismiss' => 'alert', type: 'button' }
      %span{ 'aria-hidden' => 'true' } ×
    %strong
      = message

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    %span.text-muted= t('.copyright')

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  %button.navbar-toggler.navbar-toggler-right{ 'aria-controls' => 'navbar-supported-content',
  'aria-expanded' => 'false',
  'aria-label' => 'Toggle navigation',
  'data-target' => '#navbar-supported-content',
  'data-toggle' => 'collapse',
  type: 'button' }
    %span.navbar-toggler-icon

  %a.navbar-brand{ href: root_path }= t('.title')
  .collapse.navbar-collapse#navbar-supported-content
    %ul.navbar-nav.mr-auto
      %li.nav-item
        = link_to t('.rentals'), rentals_path, class: 'nav-link'

    %ul.navbar-nav.my-2.my-lg-0
      - if user_signed_in?
        = link_to current_user.decorate.full_name_with_logout,
        destroy_user_session_path,
        method: :delete, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title= t('.title')
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{ content: 'IE=edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }
  %body
    = render 'layouts/header'
    %main.container{ role: 'main' }
      = render 'layouts/flash_messages'
      = yield
= render 'layouts/footer'

app/views/rentals/_rental.html.haml
%tr
  %td= rental.book.title
  %td= rental.user.decorate.full_name
  %td= rental.status
  %td= rental.created_at.to_s(:short)

app/views/rentals/index.html.haml
%h1
  = Rental.model_name.plural.humanize

%table.table.table-striped
  %thead
    %th{scope: 'col'}= Book.human_attribute_name(:title)
    %th{scope: 'col'}= t('full_name')
    %th{scope: 'col'}= Rental.human_attribute_name(:status)
    %th{scope: 'col'}= t('date')

    %tbody
      = render @rentals